[package]
name = "block_in_place"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3"
os_pipe = "1.0"
tokio = { version = "1.16", features = ["fs", "rt-multi-thread"] }
tokio-util = { version = "0.7", features = ["io"] }
